name: SSH and Execute Commands with Password

on:
  workflow_dispatch:
  schedule:
    # 每两小时执行一次
    - cron: '0 */1 * * *'

jobs:
  ssh-execute:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install sshpass
      run: |
        # 安装 sshpass
        sudo apt-get update
        sudo apt-get install -y sshpass

    - name: Execute Commands with sshpass
      env:
        SERVER_SSH: s7.serv00.com
        USER1: wc453707243
        PASS1: ${{ secrets.PASS1 }} # 确保将密码存储在 secrets 中
        USER2: wc453707244
        PASS2: ${{ secrets.PASS2 }} # 确保将密码存储在 secrets 中
      run: |
        # 使用 sshpass 执行命令，禁用 StrictHostKeyChecking
        sshpass -p "${PASS1}" ssh -o StrictHostKeyChecking=no ${USER1}@${SERVER_SSH} "cd domains/wc453707243.serv00.net/ && screen -dmS vless node /home/wc453707243/domains/wc453707243.serv00.net/vless/app.js"
        sshpass -p "${PASS2}" ssh -o StrictHostKeyChecking=no ${USER2}@${SERVER_SSH} "cd domains/wc453707244.serv00.net/ && screen -dmS vless node /home/wc453707244/domains/wc453707244.serv00.net/vless/app.js"
