name: SSH and Execute Commands

on:
  workflow_dispatch:
  schedule:
    # 每2小时执行一次
    - cron: '0 */2 * * *'

jobs:
  ssh-execute:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup SSH Key
      run: |
        # 创建 SSH 目录
        mkdir -p ~/.ssh
        # 写入私钥到 id_rsa 文件
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        # 设置私钥文件权限
        chmod 600 ~/.ssh/id_rsa

    - name: Setup SSH Configuration
      run: |
        # 创建 SSH 配置文件
        echo -e "Host *\n  StrictHostKeyChecking no\n  PasswordAuthentication no\n  CheckHostIP no\n  IdentitiesOnly yes\n  IdentityFile ~/.ssh/id_rsa" > ~/.ssh/config

    - name: Display SSH Configuration
      run: |
        # 显示 SSH 配置文件内容
        cat ~/.ssh/config

    - name: Add Server to Known Hosts
      run: |
        # 将服务器 IP 添加到 known_hosts 文件
        ssh-keyscan -H "s7.serv00.com" >> ~/.ssh/known_hosts

    - name: Execute Commands
      env:
        SERVER_IP: s7.serv00.com
        SERVER_USER_1: wc453707243
        SERVER_USER_2: wc453707244
      run: |
        # 使用 SSH 执行命令
        ssh -o IdentitiesOnly=yes -i ~/.ssh/id_rsa ${{ env.SERVER_USER_1 }}@${SERVER_IP} "cd domains/wc453707243.serv00.net/ && screen -S vless node /home/wc453707243/domains/wc453707243.serv00.net/vless/app.js && screen -r vless"
        ssh -o IdentitiesOnly=yes -i ~/.ssh/id_rsa ${{ env.SERVER_USER_2 }}@${SERVER_IP} "cd domains/wc453707244.serv00.net/ && screen -S vless node /home/wc453707244/domains/wc453707244.serv00.net/vless/app.js && screen -r vless"
