name: SSH Vless Keepalive

on:
  schedule:
    # 每两小时运行一次
    - cron: '0 */2 * * *'
  workflow_dispatch:  # 添加手动触发选项

jobs:
  keepalive:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Check and Install SSH and Expect
      run: |
        if ! command -v ssh &> /dev/null; then
          echo "SSH 未安装，正在安装..."
          sudo apt-get update && sudo apt-get install -y openssh-client
        else
          echo "SSH 已安装，跳过安装步骤"
        fi
        
        if ! command -v expect &> /dev/null; then
          echo "Expect 未安装，正在安装..."
          sudo apt-get update && sudo apt-get install -y expect
        else
          echo "Expect 已安装，跳过安装步骤"
        fi

    - name: Execute SSH commands for wc453707243
      env:
        SSH_HOST: ${{ secrets.SSH_HOST }}
        SSH_USER: wc453707243
        SSH_PASSWORD: ${{ secrets.SSH_PASSWORD }}
      run: |
        expect <<EOF
        set timeout 60
        spawn ssh -o StrictHostKeyChecking=no $SSH_USER@$SSH_HOST
        expect {
          "(yes/no)" {send "yes\r"; exp_continue}
          "password:" {
            send "$SSH_PASSWORD\r"
            exp_continue
          }
          "Permission denied" {
            send_user "Permission denied for wc453707243. Please check the password or SSH configuration.\n"
            exit 1
          }
          "$ " {
            send "echo '登录成功：wc453707243'\r"
            send "cd domains/${SSH_USER}.serv00.net/ && screen -S vless node /home/${SSH_USER}/domains/${SSH_USER}.serv00.net/vless/app.js && screen -r vless\r"
            send "echo '命令执行成功：wc453707243'\r"
            send "exit\r"
          }
        }
        expect eof
        EOF

    - name: Execute SSH commands for wc453707244
      env:
        SSH_HOST: ${{ secrets.SSH_HOST }}
        SSH_USER: wc453707244
        SSH_PASSWORD: ${{ secrets.SSH_PASSWORD }}
      run: |
        expect <<EOF
        set timeout 60
        spawn ssh -o StrictHostKeyChecking=no $SSH_USER@$SSH_HOST
        expect {
          "(yes/no)" {send "yes\r"; exp_continue}
          "password:" {
            send "$SSH_PASSWORD\r"
            exp_continue
          }
          "Permission denied" {
            send_user "Permission denied for wc453707244. Please check the password or SSH configuration.\n"
            exit 1
          }
          "$ " {
            send "echo '登录成功：wc453707244'\r"
            send "cd domains/${SSH_USER}.serv00.net/ && screen -S vless node /home/${SSH_USER}/domains/${SSH_USER}.serv00.net/vless/app.js && screen -r vless\r"
            send "echo '命令执行成功：wc453707244'\r"
            send "exit\r"
          }
        }
        expect eof
        EOF
