name: SSH Vless Keepalive

on:
  workflow_dispatch:
  schedule:
    # 每两小时运行一次
    - cron: '0 */2 * * *'

jobs:
  keepalive:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install SSH and Expect
      run: sudo apt-get update && sudo apt-get install -y openssh-client expect

    - name: Execute SSH commands for User 1
      env:
        SSH_HOST: ${{ secrets.SSH_HOST }}
        SSH_USER: ${{ secrets.SSH_USER1 }}
        SSH_PASSWORD: ${{ secrets.SSH_PASSWORD }}
      run: |
        expect <<EOF
        spawn ssh $SSH_USER@$SSH_HOST
        expect "password:"
        send "$SSH_PASSWORD\r"
        expect "$ "
        send "cd domains/${{ secrets.SSH_USER1 }}.serv00.net/ && screen -S vless node /home/${{ secrets.SSH_USER1 }}/domains/${{ secrets.SSH_USER1 }}.serv00.net/vless/app.js && screen -r vless\r"
        expect "$ "
        send "exit\r"
        expect eof
        EOF

    - name: Execute SSH commands for User 2
      env:
        SSH_HOST: ${{ secrets.SSH_HOST }}
        SSH_USER: ${{ secrets.SSH_USER2 }}
        SSH_PASSWORD: ${{ secrets.SSH_PASSWORD }}
      run: |
        expect <<EOF
        spawn ssh $SSH_USER@$SSH_HOST
        expect "password:"
        send "$SSH_PASSWORD\r"
        expect "$ "
        send "cd domains/${{ secrets.SSH_USER2 }}.serv00.net/ && screen -S vless node /home/${{ secrets.SSH_USER2 }}/domains/${{ secrets.SSH_USER2 }}.serv00.net/vless/app.js && screen -r vless\r"
        expect "$ "
        send "exit\r"
        expect eof
        EOF
